// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJnWm3-WlB4UR59bwjZ_Zvzdnl2QmLBa8',
    appId: '1:674693913539:web:951591087e36cf33627b76',
    messagingSenderId: '674693913539',
    projectId: 'flutter-chat-552bf',
    authDomain: 'flutter-chat-552bf.firebaseapp.com',
    storageBucket: 'flutter-chat-552bf.appspot.com',
    measurementId: 'G-2GTV8H8H81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4ZBRnP7vKA1RWgvJOpX7x1ycS1tAkGQ',
    appId: '1:674693913539:android:632905e315bfa1fd627b76',
    messagingSenderId: '674693913539',
    projectId: 'flutter-chat-552bf',
    storageBucket: 'flutter-chat-552bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA8ENXuX7fasWAWtBWwU5GUghrwD8QgB4',
    appId: '1:674693913539:ios:8c85f1c8fc69c06b627b76',
    messagingSenderId: '674693913539',
    projectId: 'flutter-chat-552bf',
    storageBucket: 'flutter-chat-552bf.appspot.com',
    iosClientId: '674693913539-7pi86qec4blqpq1jprm0le6jh11lfcpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA8ENXuX7fasWAWtBWwU5GUghrwD8QgB4',
    appId: '1:674693913539:ios:8c85f1c8fc69c06b627b76',
    messagingSenderId: '674693913539',
    projectId: 'flutter-chat-552bf',
    storageBucket: 'flutter-chat-552bf.appspot.com',
    iosClientId: '674693913539-7pi86qec4blqpq1jprm0le6jh11lfcpq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
